metadata.allow-direct-references = true

[version]
source = "vcs"

[build.targets.sdist]
exclude = [
    "/.github",
]

[build.targets.wheel]
artifacts = [
  "/singleparticle/_vendored/TiPi/target/TiPi-for-spfluo-*.jar",
  "/singleparticle/web/client/dist/*"
]
packages = ["singleparticle"]

[build.targets.wheel.hooks.custom]

[envs.default]
installer = "uv"
dependencies = ["scipion-app @ git+ssh://git@github.com/jplumail/scipion-app@fluo", "napari[pyqt5]"]

[[envs.default.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]

[envs.default.scripts]
test = "python -m scipion tests singleparticle.tests.test_protocols_classic_workflow --run"