[build-system]
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0"
]

[project]
dynamic = ["version"]
[tool.setuptools_scm]

[tool.ruff]
select = [
    "E", "F", # default
    "I", # isort
]

[tool.ruff.isort]
known-first-party = ["singleparticle"]
known-third-party = ["pyworflow", "pwfluo"]